apiVersion: apps/v1
kind: Deployment
metadata: 
  name: chromadb-deployment
spec:
  selector:
    matchLabels:
      app: chromadb
  replicas: 2
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
      - name: chromadb
        image: snikpic/chromadb:latest
        ports:
        - containerPort: 3889