apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: chromadb-deployment
spec:
  selector:
    matchLabels:
      app: chromadb
  replicas: 2
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
      - name: chromadb
        image: snikpic/chromadb:latest
        ports:
        - containerPort: 8080